spring:
  application:
    name: ms-customer
  cloud:
    config:
      uri: http://52.226.144.128:8888
      username: admin
      password: nttdatacorazon
  config:
    import: optional:configserver:http://52.226.144.128:8888
